"""Update unique constraint on sale

Revision ID: 0b441d9c8f54
Revises: 
Create Date: 2025-07-08 16:31:11.428470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b441d9c8f54'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('_user_sale_name_uc'), type_='unique')
        batch_op.create_unique_constraint('_user_sale_name_uc', ['user_id', 'sale_date', 'article_name', 'client_name', 'price_unit'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_constraint('_user_sale_name_uc', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('_user_sale_name_uc'), ['user_id', 'sale_date', 'article_name', 'client_name'])

    # ### end Alembic commands ###
