"""Add notes column to Article

Revision ID: af88bdafb2d7
Revises: 0b441d9c8f54
Create Date: 2025-10-20 19:06:20.267433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af88bdafb2d7'
down_revision = '0b441d9c8f54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
